// Code generated by "stringer -type=direction"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[up-0]
	_ = x[down-1]
	_ = x[left-2]
	_ = x[right-3]
}

const _direction_name = "updownleftright"

var _direction_index = [...]uint8{0, 2, 6, 10, 15}

func (i direction) String() string {
	if i < 0 || i >= direction(len(_direction_index)-1) {
		return "direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _direction_name[_direction_index[i]:_direction_index[i+1]]
}
